stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  image: python:latest
  stage: deploy
  environment:
    name: prod
    url: https://annualproject-api.io/
  only:
   - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://annual-project --recursive
    - aws s3 sync ./dist s3://annual-project --acl public-read
